"""empty message

Revision ID: fd499aef41ab
Revises: 
Create Date: 2023-08-24 12:55:04.332361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd499aef41ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vk_id'), ['vk_id'], unique=True)

    op.create_table('users_with_access_to_the_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('access', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_with_access_to_the_panel'))
    )
    with op.batch_alter_table('users_with_access_to_the_panel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_with_access_to_the_panel_vk_id'), ['vk_id'], unique=True)

    op.create_table('location_of_notifications_at_the_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_location_of_notifications_at_the_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_of_notifications_at_the_user'))
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.drop_table('location_of_notifications_at_the_user')
    with op.batch_alter_table('users_with_access_to_the_panel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_with_access_to_the_panel_vk_id'))

    op.drop_table('users_with_access_to_the_panel')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vk_id'))

    op.drop_table('user')
    # ### end Alembic commands ###
